import { writeFile } from "fs/promises";
import { join } from "path";
import * as prettier from "prettier";
import { getComponentDeclaration } from "../component-declaration-file";
import { getComponentGlobalTypeDeclaration } from "../global-type-declarations/get-global-type-declaration";
import { processAutoGeneratedFile } from "../global-type-declarations/replace-auto-generated-content";
import { extractLibraryComponents } from "./generator";

const startTime = performance.now();

export const getLibrarySummary = (relativeComponentsSrcPath: string) =>
  extractLibraryComponents(join(process.cwd(), relativeComponentsSrcPath));

export const generateLibrarySummary = async (
  relativeComponentsSrcPath: string,
  resultFileName = "library-summary.ts"
) => {
  const libraryComponents = await getLibrarySummary(relativeComponentsSrcPath);
  const componentsDeclarationFile = getComponentDeclaration(libraryComponents);

  return Promise.all([
    ...libraryComponents.map(component =>
      processAutoGeneratedFile(
        join(process.cwd(), relativeComponentsSrcPath, component.srcPath),
        getComponentGlobalTypeDeclaration(component)
      )
    ),

    writeFile(
      join(process.cwd(), relativeComponentsSrcPath, resultFileName),
      `export const result = ${await prettier.format(JSON.stringify(libraryComponents, undefined, 2), { parser: "typescript" })}`
    ),
    writeFile(
      join(process.cwd(), relativeComponentsSrcPath, "components.ts"),
      componentsDeclarationFile
    )
  ]);
};

generateLibrarySummary("src/");

console.log("Elapsed time:", performance.now() - startTime);
