import { readFile, writeFile } from "fs/promises";
import { dirname, join } from "path";
import * as prettier from "prettier";
import { fileURLToPath } from "url";
import { getComponentDeclaration } from "../component-declaration-file";
import { copyAllTypesUsedByInterfaces } from "./copy-all-types-used-by-interfaces";
import { extractLibraryComponents } from "./generator";
import type { ComponentDefinition } from "./types";

const startTime = performance.now();

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const DEFAULT_DECLARATION_FILE_NAME = "components.ts";
const DEFAULT_DECLARATION_FOR_ALL_COPIED_TYPES = "component-copied-types.ts";
const DEFAULT_LIBRARY_SUMMARY_FILE_NAME = "library-summary.ts";
const DEFAULT_COMPONENT_ACCESS =
  "public" satisfies ComponentDefinition["access"];

const librarySummaryTypes = await readFile(
  join(__dirname, "./types.ts"),
  "utf-8"
);

export const getLibrarySummary = (options: {
  relativeComponentsSrcPath: string;
  defaultComponentAccess: ComponentDefinition["access"];
  excludedPaths: string[] | undefined;
  fileNameExtension: string;
}) =>
  extractLibraryComponents({
    searchPath: join(process.cwd(), options.relativeComponentsSrcPath),
    defaultComponentAccess: options.defaultComponentAccess,
    excludedPaths: options.excludedPaths,
    fileNameExtension: options.fileNameExtension
  });

export const generateLibrarySummary = async (options: {
  declarationFileName?: string;
  declarationForAllCopiedTypesFileName?: string;
  defaultComponentAccess?: ComponentDefinition["access"];
  excludedPaths?: string[];
  fileNameExtension: string;
  librarySummaryFileName?: string;
  relativeComponentsSrcPath: string;
}) => {
  const {
    declarationFileName,
    declarationForAllCopiedTypesFileName,
    defaultComponentAccess,
    excludedPaths,
    fileNameExtension,
    librarySummaryFileName,
    relativeComponentsSrcPath
  } = options;

  const libraryComponents = await getLibrarySummary({
    relativeComponentsSrcPath,
    defaultComponentAccess: defaultComponentAccess ?? DEFAULT_COMPONENT_ACCESS,
    excludedPaths,
    fileNameExtension
  });
  const componentsDeclarationFile = getComponentDeclaration(
    libraryComponents.filter(component => component.access === "public")
  );

  return Promise.allSettled([
    // ...libraryComponents.map(component =>
    //   processAutoGeneratedFile(
    //     join(process.cwd(), relativeComponentsSrcPath, component.srcPath),
    //     getComponentGlobalTypeDeclaration(component)
    //   )
    // ),

    writeFile(
      join(
        process.cwd(),
        relativeComponentsSrcPath,
        declarationForAllCopiedTypesFileName ??
          DEFAULT_DECLARATION_FOR_ALL_COPIED_TYPES
      ),
      await copyAllTypesUsedByInterfaces(libraryComponents, "src/")
    ),

    writeFile(
      join(
        process.cwd(),
        relativeComponentsSrcPath,
        librarySummaryFileName ?? DEFAULT_LIBRARY_SUMMARY_FILE_NAME
      ),
      await prettier.format(
        `export const librarySummary = ${JSON.stringify(libraryComponents, undefined, 2)} as const satisfies LibraryComponents;\n\n${librarySummaryTypes}`,
        { parser: "typescript", trailingComma: "none" }
      )
    ),
    writeFile(
      join(
        process.cwd(),
        relativeComponentsSrcPath,
        declarationFileName ?? DEFAULT_DECLARATION_FILE_NAME
      ),
      componentsDeclarationFile
    )
  ]);
};

const LIT_OR_STENCIL_JS: "lit" | "stencil-js" = "stencil-js";

if (LIT_OR_STENCIL_JS === "stencil-js") {
  // Chameleon 6
  await generateLibrarySummary({
    defaultComponentAccess: "public",
    relativeComponentsSrcPath: "src/",
    excludedPaths: [
      "deprecated",
      "internal",
      "gx-grid-chameleon",
      "components/next",
      "notifications-item.tsx",
      "notifications.tsx",
      "components/paginator/",
      "test-flexible-layout.tsx",
      "timer.tsx",
      "showcase.tsx"
    ],
    fileNameExtension: ".tsx"
  });
} else {
  await generateLibrarySummary({
    defaultComponentAccess: "private",
    relativeComponentsSrcPath: "src/",
    fileNameExtension: ".lit.ts"
  });
}

console.log(
  "Elapsed time:",
  ((performance.now() - startTime) / 1000).toFixed(3) + "s"
);

