import { writeFile } from "fs/promises";
import { join } from "path";
import * as prettier from "prettier";
import { getComponentDeclaration } from "../component-declaration-file";
import { getComponentGlobalTypeDeclaration } from "../global-type-declarations/get-global-type-declaration";
import { processAutoGeneratedFile } from "../global-type-declarations/replace-auto-generated-content";
import { extractLibraryComponents } from "./generator";
import type { ComponentDefinition } from "./types";

const startTime = performance.now();

const DEFAULT_DECLARATION_FILE_NAME = "components.d.ts";
const DEFAULT_LIBRARY_SUMMARY_FILE_NAME = "library-summary.ts";
const DEFAULT_COMPONENT_ACCESS =
  "public" satisfies ComponentDefinition["access"];

export const getLibrarySummary = (
  relativeComponentsSrcPath: string,
  defaultComponentAccess: ComponentDefinition["access"]
) =>
  extractLibraryComponents(
    join(process.cwd(), relativeComponentsSrcPath),
    defaultComponentAccess
  );

export const generateLibrarySummary = async (options: {
  declarationFileName?: string;
  defaultComponentAccess?: ComponentDefinition["access"];
  relativeComponentsSrcPath: string;
  librarySummaryFileName?: string;
}) => {
  const {
    declarationFileName,
    defaultComponentAccess,
    librarySummaryFileName,
    relativeComponentsSrcPath
  } = options;

  const libraryComponents = await getLibrarySummary(
    relativeComponentsSrcPath,
    defaultComponentAccess ?? DEFAULT_COMPONENT_ACCESS
  );
  const componentsDeclarationFile = getComponentDeclaration(libraryComponents);

  return Promise.allSettled([
    ...libraryComponents.map(component =>
      processAutoGeneratedFile(
        join(process.cwd(), relativeComponentsSrcPath, component.srcPath),
        getComponentGlobalTypeDeclaration(component)
      )
    ),

    writeFile(
      join(
        process.cwd(),
        relativeComponentsSrcPath,
        librarySummaryFileName ?? DEFAULT_LIBRARY_SUMMARY_FILE_NAME
      ),
      `export const librarySummary = ${await prettier.format(JSON.stringify(libraryComponents, undefined, 2), { parser: "typescript" })}`
    ),
    writeFile(
      join(
        process.cwd(),
        relativeComponentsSrcPath,
        declarationFileName ?? DEFAULT_DECLARATION_FILE_NAME
      ),
      componentsDeclarationFile
    )
  ]);
};

await generateLibrarySummary({
  defaultComponentAccess: "private",
  relativeComponentsSrcPath: "src/"
});

console.log(
  "Elapsed time:",
  ((performance.now() - startTime) / 1000).toFixed(3) + "s"
);

