name: CI
permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  core:
    uses: ./.github/workflows/common-ci-checks.yml
    with:
      cache: true
      publish: false
      package: "packages/core"

  webkit:
    uses: ./.github/workflows/common-ci-checks.yml
    with:
      cache: true
      publish: false
      package: "packages/webkit"
