name: CI
permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    uses: ./.github/workflows/common-ci-checks.yml
    with:
      cache: true
      publish: false
      package: "packages/build"

  core:
    uses: ./.github/workflows/common-ci-checks.yml
    with:
      cache: true
      publish: false
      package: "packages/core"

  insights:
    uses: ./.github/workflows/common-ci-checks.yml
    with:
      cache: true
      publish: false
      package: "packages/insights"

  signals:
    uses: ./.github/workflows/common-ci-checks.yml
    with:
      cache: true
      publish: false
      package: "packages/signals"

  vite-plugin:
    uses: ./.github/workflows/common-ci-checks.yml
    with:
      cache: true
      publish: false
      package: "packages/plugins/vite-plugin-kasstor"

  webkit:
    uses: ./.github/workflows/common-ci-checks.yml
    with:
      cache: true
      publish: false
      package: "packages/webkit"

