name: Publish Packages

on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  check-version:
    runs-on: ubuntu-latest
    outputs:
      core-changed: ${{ steps.check-core.outputs.version-changed }}
      insights-changed: ${{ steps.check-insights.outputs.version-changed }}
      signals-changed: ${{ steps.check-signals.outputs.version-changed }}
      vite-plugin-changed: ${{ steps.check-vite-plugin.outputs.version-changed }}
      webkit-changed: ${{ steps.check-webkit.outputs.version-changed }}
    steps:
      # Pinning to a specific commit hash for security reasons.
      # This hash corresponds to version 4.3.0 of the actions/checkout action.
      # To update, find the desired commit hash from the releases page:
      # https://github.com/actions/checkout/releases
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955

      - name: Get the latest Kasstor Core version
        id: get-latest-core-version
        run: |
          PACKAGE_NAME=@genexus/kasstor-core
          LATEST_CORE_VERSION=$(curl -s https://registry.npmjs.org/$PACKAGE_NAME | jq -r '.["dist-tags"].latest')
          echo "latest_core_version=$LATEST_CORE_VERSION" >> $GITHUB_ENV

      - name: Get the latest Kasstor Insights version
        id: get-latest-insights-version
        run: |
          PACKAGE_NAME=@genexus/kasstor-insights
          LATEST_INSIGHTS_VERSION=$(curl -s https://registry.npmjs.org/$PACKAGE_NAME | jq -r '.["dist-tags"].latest')
          echo "latest_insights_version=$LATEST_INSIGHTS_VERSION" >> $GITHUB_ENV

      - name: Get the latest Kasstor Signals version
        id: get-latest-signals-version
        run: |
          PACKAGE_NAME=@genexus/kasstor-signals
          LATEST_SIGNALS_VERSION=$(curl -s https://registry.npmjs.org/$PACKAGE_NAME | jq -r '.["dist-tags"].latest')
          echo "latest_signals_version=$LATEST_SIGNALS_VERSION" >> $GITHUB_ENV

      - name: Get the latest Vite Plugin Kasstor version
        id: get-latest-vite-plugin-version
        run: |
          PACKAGE_NAME=@genexus/vite-plugin-kasstor
          LATEST_VITE_PLUGIN_VERSION=$(curl -s https://registry.npmjs.org/$PACKAGE_NAME | jq -r '.["dist-tags"].latest')
          echo "latest_vite_plugin_version=$LATEST_VITE_PLUGIN_VERSION" >> $GITHUB_ENV

      - name: Get the latest Kasstor Webkit version
        id: get-latest-webkit-version
        run: |
          PACKAGE_NAME=@genexus/kasstor-webkit
          LATEST_WEBKIT_VERSION=$(curl -s https://registry.npmjs.org/$PACKAGE_NAME | jq -r '.["dist-tags"].latest')
          echo "latest_webkit_version=$LATEST_WEBKIT_VERSION" >> $GITHUB_ENV

      - name: Print last published versions
        run: |
          echo "The latest Kasstor Core version is ${{ env.latest_core_version }}"
          echo "The latest Kasstor Insights version is ${{ env.latest_insights_version }}"
          echo "The latest Kasstor Signals version is ${{ env.latest_signals_version }}"
          echo "The latest Vite Plugin Kasstor version is ${{ env.latest_vite_plugin_version }}"
          echo "The latest Kasstor Webkit version is ${{ env.latest_webkit_version }}"

      - name: Check if `core` version changed
        id: check-core
        run: |
          CURRENT_VERSION=$(jq -r .version packages/core/package.json)
          PREVIOUS_VERSION=${{ env.latest_core_version }}
          if [ "$CURRENT_VERSION" != "$PREVIOUS_VERSION" ]; then
            echo "Version changed!"
            echo "version-changed=true" >> $GITHUB_OUTPUT
          else
            echo "version-changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Check if `insights` version changed
        id: check-insights
        run: |
          CURRENT_VERSION=$(jq -r .version packages/insights/package.json)
          PREVIOUS_VERSION=${{ env.latest_insights_version }}
          if [ "$CURRENT_VERSION" != "$PREVIOUS_VERSION" ]; then
            echo "Version changed!"
            echo "version-changed=true" >> $GITHUB_OUTPUT
          else
            echo "version-changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Check if `signals` version changed
        id: check-signals
        run: |
          CURRENT_VERSION=$(jq -r .version packages/signals/package.json)
          PREVIOUS_VERSION=${{ env.latest_signals_version }}
          if [ "$CURRENT_VERSION" != "$PREVIOUS_VERSION" ]; then
            echo "Version changed!"
            echo "version-changed=true" >> $GITHUB_OUTPUT
          else
            echo "version-changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Check if `vite-plugin` version changed
        id: check-vite-plugin
        run: |
          CURRENT_VERSION=$(jq -r .version packages/plugins/vite-plugin-kasstor/package.json)
          PREVIOUS_VERSION=${{ env.latest_vite_plugin_version }}
          if [ "$CURRENT_VERSION" != "$PREVIOUS_VERSION" ]; then
            echo "Version changed!"
            echo "version-changed=true" >> $GITHUB_OUTPUT
          else
            echo "version-changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Check if `webkit` version changed
        id: check-webkit
        run: |
          CURRENT_VERSION=$(jq -r .version packages/webkit/package.json)
          PREVIOUS_VERSION=${{ env.latest_webkit_version }}
          if [ "$CURRENT_VERSION" != "$PREVIOUS_VERSION" ]; then
            echo "Version changed!"
            echo "version-changed=true" >> $GITHUB_OUTPUT
          else
            echo "version-changed=false" >> $GITHUB_OUTPUT
          fi

  publish-core:
    needs: check-version
    if: needs.check-version.outputs.core-changed == 'true'
    uses: ./.github/workflows/common-ci-checks.yml
    with:
      cache: false
      publish: true
      package: "packages/core"
    secrets: inherit

  publish-insights:
    needs: check-version
    if: needs.check-version.outputs.insights-changed == 'true'
    uses: ./.github/workflows/common-ci-checks.yml
    with:
      cache: false
      publish: true
      package: "packages/insights"
    secrets: inherit

  publish-signals:
    needs: check-version
    if: needs.check-version.outputs.signals-changed == 'true'
    uses: ./.github/workflows/common-ci-checks.yml
    with:
      cache: false
      publish: true
      package: "packages/signals"
    secrets: inherit

  publish-vite-plugin:
    needs: check-version
    if: needs.check-version.outputs.vite-plugin-changed == 'true'
    uses: ./.github/workflows/common-ci-checks.yml
    with:
      cache: false
      publish: true
      package: "packages/plugins/vite-plugin-kasstor"
    secrets: inherit

  publish-webkit:
    needs: check-version
    if: needs.check-version.outputs.webkit-changed == 'true'
    uses: ./.github/workflows/common-ci-checks.yml
    with:
      cache: false
      publish: true
      package: "packages/webkit"
    secrets: inherit

